name: Node.jsCl

on:
  push:
    branches:
      -main

jobs:
build:

runs on: ubuntu-latest

strategy:
  matrix:
     node-version: [20.x]

steps:
-name: Checkout repository 
uses: Actions/setup@v3

-name: Setup node.js
uses: actions/setup-node@v3
with:
node-version: ${{matrix.nodeversion}}

-name: install dependencies 
run: npm install

-name: start application 
-run: npm start
